### ISSUE TITLE
Make the authentication code synchronous 

### ISSUE THREAD

**Issue by johnbalvin** [zelenin/go-tdlib#10]
this library it's confusing  when using it at first, just looking at the code I could understand.
When running the code you need to authenticate with your phone number, the code(whic is asynchronous) ask you for you phone number as seen here [authorization.go#L132 ](https://github.com/zelenin/go-tdlib/blob/master/client/authorization.go#L132 ), but in the console there is too much noise from other logs that someone who didn't read the code can't understand what to do next, look: 
![image](https://user-images.githubusercontent.com/25888114/62615127-4f06cf00-b8d2-11e9-916a-8e7fd9d1cc45.png)

it get lost in the whole logs 
![image](https://user-images.githubusercontent.com/25888114/62615048-2aaaf280-b8d2-11e9-8b6c-c749f203312a.png)

So it would great if when asking the phone number, this code should be synchronous so the printed part "Enter phone number: " could be vissible and don't get lost in the whole logs.

**Comment by zelenin** [comment]
you should decrease error logs level (see readme) or write your own AuthorizationStateHandler/Interactor with a better authorization method. The library (tdlib, not go-tdlib) is asynchronous.
