### ISSUE TITLE
How can I  avoid missing messages from update?

### ISSUE THREAD

**Issue by dylanpoe** [zelenin/go-tdlib#103]
I Use the following codes, to get the updates from channel, all my channel  are not muted, not archived, I can get  all the messages in the TG official released client,I can see the messages in their own channel

While in my code ,by the go-tdlib, 

for update := range listener.Updates {}
But somehow unknown reasons , some update messages are not showed in my update logs,

Could you kindly tell me how can I solve the problems?

Did it caused by the server location? My VPS is AWS ubuntu  22.04 in Singapore 

I find no clues why some message not showed ,Please help me ,thank you

**Comment by zelenin** [comment]
tdlib is a library for creating telegram clients. The library chooses which updates you need based on your behavior inside the client.
(not go-tdlib issue)

**Comment by dylanpoe** [comment]
Thank you so much
go-tdlib ,supports which version of  tdlib? 1.8.0 ?or the latest?

**Comment by zelenin** [comment]
```
Current supported version of TDLib corresponds to the commit hash [daf4801](https://github.com/tdlib/td/commit/daf480138d482e7970f6d7a681d778a98f11fdd2), updated on 2023-09-19
```

**Comment by dylanpoe** [comment]
Thank you so much!
I upgrade to the daf4801 in  https://github.com/tdlib/td and upgrade  https://github.com/zelenin/go-tdlib/ to the v0.7.0 , 
after compile https://github.com/tdlib/td  and  https://github.com/zelenin/go-tdlib/  each on my vps, ubuntu22.04,AWS,
When I running the binary I got , 
Still got the error
2023/10/12 09:56:53 NewClient error: 500 Request aborted


How could I solve it ?
Still I make an issue (https://github.com/zelenin/go-tdlib/issues/104)
Thank you for your time

**Comment by ShamanValius** [comment]
Did you manage to solve the problem?
