### ISSUE TITLE
please provide how to get all messageIds from chat

### ISSUE THREAD

**Issue by andreymelkov** [zelenin/go-tdlib#106]
Could you please provide how to get all messageIds from chat

**Comment by dylanpoe** [comment]
Check this issue proposed by me,
 https://github.com/zelenin/go-tdlib/issues/101
Already solve your issue

**Comment by andreymelkov** [comment]
> Check this issue proposed #101 Already solved your issue

But it's not the same. I want to get all chat history. For this I need to put into GetChatHistoryRequest FromMessageId variable. So, i thought that if I get all MessageIds from chat, I could get history from messageId what I need
