### ISSUE TITLE
About download messageSender's file

### ISSUE THREAD

**Issue by af913337456** [zelenin/go-tdlib#107]
I am looking for how to download the images in the picture message sent to me by the other party. As for the voice in the voice message. I looked at the function and it doesn't seem to be present. Currently, the "ReadFilePart" function can download its own files. But it seems that the sender cannot download it. Did I miss it? Can you give me some guidance, thank you.

@dezi

**Comment by andreymelkov** [comment]
> I am looking for how to download the images in the picture message sent to me by the other party. As for the voice in the voice message. I looked at the function and it doesn't seem to be present. Currently, the "ReadFilePart" function can download its own files. But it seems that the sender cannot download it. Did I miss it? Can you give me some guidance, thank you.
> 
> @dezi

when you listen updates, you can get catch updateType "updateNewMessage", update new message has Message.Content. Message Content has a few types: messageText, messagePhoto and so on. MessagePhoto has Photo. This is your file

**Comment by af913337456** [comment]
> > I am looking for how to download the images in the picture message sent to me by the other party. As for the voice in the voice message. I looked at the function and it doesn't seem to be present. Currently, the "ReadFilePart" function can download its own files. But it seems that the sender cannot download it. Did I miss it? Can you give me some guidance, thank you.
> > @dezi
> 
> when you listen updates, you can get catch updateType "updateNewMessage", update new message has Message.Content. Message Content has a few types: messageText, messagePhoto and so on. MessagePhoto has Photo. This is your file

they are the basis info, not the body bytes

**Comment by zelenin** [comment]
Have you tried ```tdlibClient.DownloadFile(...)```?

**Comment by af913337456** [comment]
> Have you tried `tdlibClient.DownloadFile(...)`?

yes, this return the *File which containes only basis info, no `[]byte` of the file.

**Comment by zelenin** [comment]
```
// Represents a file
type File struct {
	meta
	// Unique file identifier
	Id int32 `json:"id"`
	// File size, in bytes; 0 if unknown
	Size int64 `json:"size"`
	// Approximate file size in bytes in case the exact file size is unknown. Can be used to show download/upload progress
	ExpectedSize int64 `json:"expected_size"`
	// Information about the local copy of the file
	Local *LocalFile `json:"local"`
	// Information about the remote copy of the file
	Remote *RemoteFile `json:"remote"`
}
// Represents a local file
type LocalFile struct {
	meta
	// Local path to the locally available file part; may be empty
	Path string `json:"path"`
	// True, if it is possible to download or generate the file
	CanBeDownloaded bool `json:"can_be_downloaded"`
	// True, if the file can be deleted
	CanBeDeleted bool `json:"can_be_deleted"`
	// True, if the file is currently being downloaded (or a local copy is being generated by some other means)
	IsDownloadingActive bool `json:"is_downloading_active"`
	// True, if the local copy is fully available
	IsDownloadingCompleted bool `json:"is_downloading_completed"`
	// Download will be started from this offset. downloaded_prefix_size is calculated from this offset
	DownloadOffset int64 `json:"download_offset"`
	// If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix in bytes
	DownloadedPrefixSize int64 `json:"downloaded_prefix_size"`
	// Total downloaded file size, in bytes. Can be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
	DownloadedSize int64 `json:"downloaded_size"`
}
```
we have ```File.LocalFile.Path```
