### ISSUE TITLE
td version daf4801, can not receive phone code

### ISSUE THREAD

**Issue by af913337456** [zelenin/go-tdlib#108]
`Go wrapper for [TDLib (Telegram Database Library)](https://github.com/tdlib/td) with full support of the TDLib. Current supported version of TDLib corresponds to the commit hash [daf4801](https://github.com/tdlib/td/commit/daf480138d482e7970f6d7a681d778a98f11fdd2), updated on 2023-09-19`

@zelenin hello, according to this notes, i use the the `daf4801` brach and run the `demo/main.go`, but all the phone can not receive the code from telegram.

**Comment by zelenin** [comment]
any output?

**Comment by af913337456** [comment]
> any output?

`Enter code`

**Comment by zelenin** [comment]
then this is a tdlib issue

**Comment by FunkyYang** [comment]
can't receive auth code and auth code did't send to client at desktop
