### ISSUE TITLE
Please support the QrCode login

### ISSUE THREAD

**Issue by af913337456** [zelenin/go-tdlib#109]
Please support the QrCode login. @zelenin 

this can solved the phone code limitation problem. thanks alot.

**Comment by af913337456** [comment]
i support myself. sloved

**Comment by chenyu1990** [comment]
> i support myself. sloved

大佬，分析一下

**Comment by chenyu1990** [comment]
请问你有没有遇到内存泄漏的问题？就是内存一点一点慢慢增加。

**Comment by af913337456** [comment]
> > i support myself. sloved
> 
> 大佬，分享一下

机密，不好意思

**Comment by af913337456** [comment]
> 请问你有没有遇到内存泄漏的问题？就是内存一点一点在慢慢增加，释放不掉。一开始100mb不到，1个小时久1G了

没

**Comment by zelenin** [comment]
added
