### ISSUE TITLE
basic Login need improve

### ISSUE THREAD

**Issue by FunkyYang** [zelenin/go-tdlib#114]
I view demo code and make mine scene.
first I need start client and authorization to receive phone auth code.
second provide phone code to complete the rest of thing.
the problem at second .I have no idea to call ```Auth(client,authorization)``` because it's inner method .

**Comment by FunkyYang** [comment]
enter phone code and enter code must in ```client.newClient(author)``` ?

**Comment by FunkyYang** [comment]
enter phone  number  and enter phone code must in client.newClient(author) ? which one can be break? I mean I provide this on web.and when user enter them phone number and then they will be reveived a phone auth code,they use this phont auth code to complete the rest of thing.but I wonder why ```client.newClient()``` could not be executed twice and I don't call ```client.newClient()``` which could not call ```state, ok := <-t.authorization.State:```,how to fix it ?

**Comment by FunkyYang** [comment]
enter phone number and enter phone code must in client.newClient(author) ? which one can be break? I mean I provide this on web.and when user enter them phone number and then they will be reveived a phone auth code,they use this phone auth code to Ｅcomplete the rest of thing.but I wonder why client.newClient() could not be executed twice and I don't call client.newClient() which could not call state, ok := <-t.authorization.State:,how to fix it ?

**Comment by FunkyYang** [comment]
enter phone number and enter phone code must in client.newClient(author) ? which one can be break? I mean I provide this on web.and when user enter them phone number and then they will be reveived a phone auth code,they use this phone auth code to complete the rest of thing.but I wonder why client.newClient() could not be executed twice and I don't call client.newClient() which could not call state, ok := <-t.authorization.State:,how to fix it ?

**Comment by FunkyYang** [comment]
enter phone number and enter phone code must in ```client.NewClient(authorizer)``` ?, which one can be break? I mean I provide this on web and user enter them phone number , they will be reveived a phone auth code soon,then they use this phone auth code to complete the rest of thing.but I wonder why ```client.NewClient(authorizer)``` could not be executed twice and I don't call ```client.NewClient(authorizer)``` which could not call ``` state, ok := <-t.authorization.State:``` in ```go client.CliInteractor(authorizer)``` how to fix it ?

**Comment by zelenin** [comment]
I think you should implement ```AuthorizationStateHandler``` with your logic and pass it to NewClient. ```clientAuthorizer``` and ```botAuthorizer``` are examples of implementations

https://github.com/zelenin/go-tdlib/blob/master/client/client.go#L46
https://github.com/zelenin/go-tdlib/blob/master/client/authorization.go#L63
https://github.com/zelenin/go-tdlib/blob/master/client/authorization.go#L186

**Comment by FunkyYang** [comment]
@zelenin I had implement ```AuthorizationStateHandler```.but the key is that which could be provide auth code on old client

**Comment by FunkyYang** [comment]
@zelenin it seems a problem when I provide a phone auth code to  ```AuthorizationStateHandler``` and can't trigger to call ```	err := Authorize(client, authorizationStateHandler)```　in NewClient ,what should I do ?

**Comment by FunkyYang** [comment]
@zelenin when I received ```TypeAuthorizationStateWaitCode```
```
for {
		state, err := client.GetAuthorizationState()
		...
	}
```
can't exexute looply ? what can I do to keep it up?

**Comment by FunkyYang** [comment]
@zelenin when I received TypeAuthorizationStateWaitCode and the phone auth code I had received .what should I do next?
it seems like 
for {
		state, err := client.GetAuthorizationState()
		...
	}
can't exexute looply ? what can I do to keep it up?

**Comment by FunkyYang** [comment]
sloved  provide phone code to ```AuthorizationStateHandler State ``` make the code above looply and state comes  ```TypeAuthorizationStateReady```
