### ISSUE TITLE
how to set @extra

### ISSUE THREAD

**Issue by chenyu1990** [zelenin/go-tdlib#115]
https://github.com/tdlib/td/blob/6ee64289f3666774fb694c9d33f83ed8bd52b60c/td/telegram/td_json_client.h#L22

I want to match the request and response in the GetListener

**Comment by zelenin** [comment]
already implemented here
https://github.com/zelenin/go-tdlib/blob/master/client/client.go#L101

**Comment by chenyu1990** [comment]
request.meta is m, not M
Cannot write externally

**Comment by chenyu1990** [comment]
Maybe there is something wrong with my expression. I use translator.
When requesting a ForwardMessages, the response returned immediately is not the final result.
The event listened to in GetListener is the final result.
.Send cannot associate GetListener with ForwardMessages.
Can I maintain extra myself?

**Comment by zelenin** [comment]
> When requesting a .ForwardMessages, the response returned immediately is not the final result.

the response is not returned synchronously. Under the hood, ```ForwardMessages``` method uses ```Send``` method, which sets ```Extra``` to request, and then catches response and returns it as a ```ForwardMessages``` response. So the library is already doing what you want to achieve

https://github.com/zelenin/go-tdlib/blob/master/client/client.go#L119
