### ISSUE TITLE
Any one has the following  question？

### ISSUE THREAD

**Issue by dylanpoe** [zelenin/go-tdlib#119]
I have 2 numbers banned  like that, anyone has before ? 
how to solve the issue?
[ 1][t 4][1700228281.275236606][Session.cpp:961][#1][!Session:1:main]  Your phone number was banned for suspicious activity. If you think that this is a mistake, please try to log in from an official mobile app and send a email to recover the account by following instructions provided by the app.

**Comment by zelenin** [comment]
https://www.reddit.com/r/Telegram/comments/15y0dh9/tdlib_and_spamming/
