### ISSUE TITLE
SetProfilePhoto got error.

### ISSUE THREAD

**Issue by chenyu1990** [zelenin/go-tdlib#129]
`ok, err := tl.Client.SetProfilePhoto(&client.SetProfilePhotoRequest{
							Photo: &client.InputChatPhotoStatic{
								Photo: &client.InputFileRemote{Id: telegramUser.PhotoRemoteId},
							},
							IsPublic: true,
						})`

got error:
`400 Can't use file of type ChatPhoto as Photo`

**Comment by zelenin** [comment]
check the tdlib version. It must match the tdlib version from the README
