### ISSUE TITLE
Fail to run on Windows build

### ISSUE THREAD

**Issue by perqin** [zelenin/go-tdlib#133]
I've followed the [official instruction](https://tdlib.github.io/td/build.html?language=Go) to build, with the selection:
- Build the debug binary: Unchecked
- Shell application: PowerShell
- bitness: 64

For reference, here's the instruction on that page:

> Note that Windows Subsystem for Linux (WSL) and Cygwin are not Windows environments, so you need to use instructions for Linux for them instead.
> Download and install [Microsoft Visual Studio](https://visualstudio.microsoft.com/vs/community/). Enable C++ support while installing.
> Download and install [CMake](https://cmake.org/download/); choose "Add CMake to the system PATH" option while installing.
> Download and install [Git](https://git-scm.com/download/win).
> Download and unpack [PHP](https://windows.php.net/download). Add the path to php.exe to the PATH environment variable.
> Close and re-open PowerShell if the PATH environment variable was changed.
> Run these commands in PowerShell to build TDLib and to install it to td/tdlib:
>
> ```
> git clone https://github.com/tdlib/td.git
> cd td
> git clone https://github.com/Microsoft/vcpkg.git
> cd vcpkg
> git checkout cd5e746ec203c8c3c61647e0886a8df8c1e78e41
> ./bootstrap-vcpkg.bat
> ./vcpkg.exe install gperf:x64-windows openssl:x64-windows zlib:x64-windows
> cd ..
> Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
> mkdir build
> cd build
> cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
> cmake --build . --target install --config Release
> cd ..
> cd ..
> dir td/tdlib
> ```

I placed the built tdlib to C:\Users\Perqin\Workspaces\tg-nep-dl-dev\tdlib-build\

```
+ tdlib-build
  + lib
  + include
  + bin
```

And set the environment variables:
- `CGO_CFLAGS=-IC:/Users/Perqin/Workspaces/tg-nep-dl-dev/tdlib-build/include`
- `CGO_ENABLED=1`
- `CGO_LDFLAGS=-LC:/Users/Perqin/Workspaces/tg-nep-dl-dev/tdlib-build/bin -ltdjson`

The build command:

```
go build -trimpath "-ldflags=-s -w" -o tgnepdl.exe tgnepdl
```

The build passes but on running the executable it fails:

```
Process finished with the exit code -1073741515 (0xC0000135)
```

My demo code:

```go
package main

import (
	"github.com/zelenin/go-tdlib/client"
	"log"
)

func main() {
	log.Println("hello")
	// client authorizer
	_ = client.ClientAuthorizer()
}
```

It even doesn't print the log.

**Comment by EllaSedova** [comment]
Try to copy all .dll files from C:/Users/Perqin/Workspaces/tg-nep-dl-dev/tdlib-build/bin to the root folder of your project

**Comment by perqin** [comment]
Oh it works! Sorry for my lack of compiling and linking knowledge :D
