### ISSUE TITLE
Error: json: cannot unmarshal object into Go struct field Messages.messages of type []*client.MessageReaction

### ISSUE THREAD

**Issue by EllaSedova** [zelenin/go-tdlib#135]
When using the **GetChatHistory()** method, the error `json: cannot unmarshal object into Go struct field Messages.messages of type []*client.MessageReaction` occurs when reading posts with comments. 
How to fix it?

**Comment by zelenin** [comment]
use the tdlib version supported by the library. See the beginning of the readme.md
