### ISSUE TITLE
NewClient error: 400 Parameters aren't specified

### ISSUE THREAD

**Issue by random1st** [zelenin/go-tdlib#142]
# Environment
MacOS 15.0
tdlib 1.8.0
go-tdlib 0.7.2

# Description
Parameters specified
```
authorizer := tdlib.ClientAuthorizer()
	go tdlib.CliInteractor(authorizer)
	authorizer.TdlibParameters <- &tdlib.SetTdlibParametersRequest{
		UseTestDc:              false,
		DatabaseDirectory:      filepath.Join(".tdlib", "database"),
		FilesDirectory:         filepath.Join(".tdlib", "files"),
		UseFileDatabase:        true,
		UseChatInfoDatabase:    true,
		UseMessageDatabase:     true,
		UseSecretChats:         false,
		ApiId:                  int32(config.ApiId),
		ApiHash:                config.ApiHash,
		SystemLanguageCode:     "en",
		DeviceModel:            "Server",
		SystemVersion:          "1.0.0",
		ApplicationVersion:     "1.0.0",
		//EnableStorageOptimizer: true, not available in go-tdlib 
		//IgnoreFileNames:        false,not available in go-tdlib
	}
```

# Error 
 NewClient error: 400 Parameters aren't specified

**Comment by chenwenbo123** [comment]
Hello, have you resolved this issue yet? I initially tried it too but ended up using other methods which didn't work well. I've realized it's an issue with the tdlib version and go-tdlib. If you have already resolved it, could you please provide some guidance on which versions of tdlib and go-tdlib you're using? Thanks.

**Comment by zelenin** [comment]
each version of go-tdlib is compatible with a specific version of tdlib (see the readme)
