### ISSUE TITLE
Static build fails due to missing tdmtproto library

### ISSUE THREAD

**Issue by amir215909** [zelenin/go-tdlib#147]
TDlib has added this library since  1.8.30.

[The issue on TDlib project](https://github.com/tdlib/td/issues/2935)

**Comment by zelenin** [comment]
static builds are really broken. thanks for the information. I'm investigating the issue

**Comment by amir215909** [comment]
The fix is already available on the same TDlib issue.

**Comment by zelenin** [comment]
fixed. the demo is updated.
