### ISSUE TITLE
Goroutine leak in receiver method of Client

### ISSUE THREAD

**Issue by amir215909** [zelenin/go-tdlib#152]
The goroutine in the line[ `go client.receiver()`  ](https://github.com/zelenin/go-tdlib/blob/43628f3fa692cfe8d8898451590d034e1e934963/client/client.go#L63) in NewClient function is leaking.

This happens when the client is closed with `Close()` method.

This occurs because [values are received from the responses channel](https://github.com/zelenin/go-tdlib/blob/43628f3fa692cfe8d8898451590d034e1e934963/client/client.go#L74) until it is closed.
Since the channel remains open, the goroutine waits for another value. However, because the client is already closed, no values are sent to the channel, causing the goroutine to wait indefinitely.

**Comment by zelenin** [comment]
fixed, v0.7.5
