### ISSUE TITLE
GetUser timeout

### ISSUE THREAD

**Issue by astravexton** [zelenin/go-tdlib#19]
```
userreq := &client.GetUserRequest{UserId: message.SenderUserId}
user, err := tdlibClient.GetUser(userreq)
```

`err` sometimes comes back with "response catching timeout", I've checked `message.SenderUserId` and it's always valid and a user, it's not my connection or anything between me and Telegram as far as I can tell. Using tdlib 1.5.0

**Comment by FunkyYang** [comment]
how sloved?
