### ISSUE TITLE
Telegram start blocking for using TDLib client

### ISSUE THREAD

**Issue by pioneerit** [zelenin/go-tdlib#20]
Hi there, FYI yesterday (04th February), around 21 GMT few accounts were blocked by Telegram.
```Your account was suspended for suspicious activity. If you think that this is a mistake, please write to recover@telegram.org your phone number and other details to recover the account.```

It happens no matter what soft was doing, 2 app was just collection data, and 1 making custom feed to and sending to the private channel. And they were running on different servers.

It happens on the previous version, I'll try to recover the account and check again on latest TDLib 1.6.0

@zelenin, I created an issue to share the information, I don't think that something wrong in the code. As it was working fine before. Some go-clients even without updates, and yesterday in 1-hour all 3 were banned.

**Comment by zelenin** [comment]
thx

**Comment by s3rj1k** [comment]
@pioneerit Same thing here. Do you have any news on this?

**Comment by pioneerit** [comment]
@s3rj1k recovery is not a problem, but I stopped all applications, and haven’t tried my hypothesis yet. And I sent an email to telegram but likely they won’t reply so fast.
