### ISSUE TITLE
Error setting verbosity level for logs

### ISSUE THREAD

**Issue by ympyst** [zelenin/go-tdlib#23]
Hello!

I try to decrease verbosity level for logging (make it 0, like in example), but I get this error:
```
[ 1][t 0][1588620837.870815516][ClientJson.cpp:90]      Failed to parse [request:{\0042@extra\0042:\0042\0042,\0042@type\0042:\0042setLogVerbosityLevel\0042,\0042new_verbosity_level\0042:0}] [Error : 0 : Unknown class]
```

This is how I make corresponding request:
```
tdlibClient, err = client.NewClient(stateHandler, logVerbosity)
_, err = tdlibClient.SetLogVerbosityLevel(&client.SetLogVerbosityLevelRequest{NewVerbosityLevel: 0})
```

Same error using `client.WithLogVerbosity` from example.

My env:
go-tdlib v0.2.0
tdlib from this image https://hub.docker.com/r/mihaildemidoff/tdlib-go

**Comment by zelenin** [comment]
it's a v1.6.0 (last for now) option.
