### ISSUE TITLE
client.go:10:18: undefined

### ISSUE THREAD

**Issue by longkeyy** [zelenin/go-tdlib#24]
go version
go version go1.13.5 darwin/amd64

# github.com/zelenin/go-tdlib/client
../../../../../go/pkg/mod/github.com/zelenin/go-tdlib@v0.2.0/client/client.go:10:18: undefined: JsonClient
../../../../../go/pkg/mod/github.com/zelenin/go-tdlib@v0.2.0/client/client.go:12:23: undefined: Response
../../../../../go/pkg/mod/github.com/zelenin/go-tdlib@v0.2.0/client/listener.go:50:16: undefined: Type

**Comment by zelenin** [comment]
do you have `../../../../../go/pkg/mod/github.com/zelenin/go-tdlib@v0.2.0/client/tdlib.go`? `JsonClient` and `Response` declared in this file.
