### ISSUE TITLE
Statically linking tdlib throws some errors

### ISSUE THREAD

**Issue by Fef0** [zelenin/go-tdlib#25]
Hi, I'm using Linux and I'm trying to compile a standalone app to send to another Linux machine without tdlib installed. 
Every time I try to run the compiled executable I get a few different errors:
```
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found 
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found
```
Any idea on how I could solve this issue? I don't know if it is related to the lib itself, but I searched online and they suggest that it could be a cross compiling issue, but actually my two machines are running the same OS, both 64 bit, so I don't know what to think. Any ideas?
Thanks in advance!

**Comment by Fef0** [comment]
Solved by updating the second machine glibc to 2.31 (>=2.29).

**Comment by khoazero123** [comment]
@Fef0 Can you guide me how to Statically linking tdlib ? I'm new with Go lang.
