### ISSUE TITLE
Problem with HTTP proxy

### ISSUE THREAD

**Issue by Spec122** [zelenin/go-tdlib#28]
`
proxy := client.WithProxy(&client.AddProxyRequest{
    Server: "ip",
    Port:   myport,
    Enable: true,
    Type: &client.ProxyTypeHttp{
    },
})
tdlibClient, err := client.NewClient(authorizer, logVerbosity, proxy)
`

(My proxy work without auth)
But when i run my code, i get this error

`[ 1][t 0][1594069996.231744528][ClientJson.cpp:76][&status.is_error()]  Failed to parse [request:{\0042@extra\0042:\004252fdfc07-2182-454f-963f-5f0f9a621d72\0042,\0042@type\0042:\0042addProxy\0042,\0042enable\0042:true,\0042port\0042:24000,\0042server\0042:\0042*IP here*\0042,\0042type\0042:{\0042@type\0042:\0042proxyTypeHttp\0042,\0042@extra\0042:\0042\0042,\0042username\0042:\0042\0042,\0042password\0042:\0042\0042,\0042http_only\0042:false}}] [Error : 0 : Unknown class]`

what i do wrong?

**Comment by zelenin** [comment]
tdlib version?

**Comment by Spec122** [comment]
> tdlib version?

1.6.0

**Comment by Spec122** [comment]
My mistake, after rebuilding the error disappeared.
