### ISSUE TITLE
Usage issue on Ubuntu for windows

### ISSUE THREAD

**Issue by imobulus** [zelenin/go-tdlib#31]
Hi,

I need to use telegram database API for automatization purposes, so I installed WSL2 and Ubuntu 20 on my windows PC and then compiled the tdlib package using instructions from [TDLib themselves](https://tdlib.github.io/td/build.html). I installed it in the $HOME/go/src/telegram.org directory, which I created just for this purpose. Then I did `go get github.com/zelenin/go-tdlib`, pasted example code from README to main.go (in another directory), and did `go build`.

It resulted in
```
imobulus@IMOBULUS-LAP:~/go/testing$ go build
# github.com/zelenin/go-tdlib/client
../src/github.com/zelenin/go-tdlib/client/tdlib.go:5:10: fatal error: td/telegram/td_json_client.h: No such file or directory
    5 | #include <td/telegram/td_json_client.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

After some research i found out that this file is located in `.../tdlib/include/td/telegram`, so i copied the whole `td` folder in there. Next `go build` looked like this
```
imobulus@IMOBULUS-LAP:~/go/testing$ go build
# github.com/zelenin/go-tdlib/client
/usr/bin/ld: cannot find -ltdjson_static
/usr/bin/ld: cannot find -ltdjson_private
/usr/bin/ld: cannot find -ltdclient
/usr/bin/ld: cannot find -ltdcore
/usr/bin/ld: cannot find -ltdactor
/usr/bin/ld: cannot find -ltddb
/usr/bin/ld: cannot find -ltdsqlite
/usr/bin/ld: cannot find -ltdnet
/usr/bin/ld: cannot find -ltdutils
collect2: error: ld returned 1 exit status
```

I haven't been able to fix this issue so far.

P.S. I tried using tdlib with [python wrapper](https://github.com/alexander-akhmetov/python-telegram). It worked like a charm, so tdlib is installed correctly.

**Comment by rusq** [comment]
I wouldn't think that this is a library problem - "it works on my machine", but I'm not on Windows.  I would suggest that this is an environment issue.

I would troubleshot this like that:

1. Was the `make install` executed for `tdlib` ?
2. Where did it install the libraries? Check if the files are really there
3. Is this directory in the PATH? If not, add it.
4. Try to compile.
5. If step (4) fails, set the [LD_LIBRARY_PATH][1] env variable to include the directory from step (2).
6. Retry step (4)

[1]: https://unix.stackexchange.com/questions/168340/where-is-ld-library-path-how-do-i-set-the-ld-library-path-env-variable

**Comment by PullDakar** [comment]
Hi, @imobulus! I have the same issue. The following steps helped me:

In this manual - "https://tdlib.github.io/td/build.html?language=Go" you must select Linux, Ubuntu ..., checkbox "Install built TDLib to /usr/local instead of placing the files to td/tdlib" and g++ compiler.

P.S. In the described commands there is one: "cmake --build. --target install". Here you may need a "sudo"
