### ISSUE TITLE
Problem with finding last seen status of the user via TDLib getFullUser method.

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#35]
Hi 
As I saw in the documentation of Telegram TDLib library:
https://core.telegram.org/method/users.getFullUser
the `getFullUser` method returns a `UserFull` object which has a field named "user" and we can find the last seen status of desired user from that.
When calling `GetUserFullInfo` method on your library, I figured out that the returning response struct of it, doesn't have a user field and also I went through the  `GetUserFullInfo` function and when I printed the marshalled response of the client, It also didn't have a "user" field.
What shall I do in order to find last seen status of a user? :🤔

**Comment by zelenin** [comment]
> As I saw in the documentation of Telegram TDLib library:
https://core.telegram.org/method/users.getFullUser

this is a mtproto docs, not tdlib.

**Comment by zelenin** [comment]
https://github.com/zelenin/go-tdlib/blob/cc7d37acc2b67d2535de4f94544b139556ff8036/client/function.go#L745
