### ISSUE TITLE
Failed to add multiple contacts via ImportContact method

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#39]
Hi everyone
I tried to iterate over csv of my phone contacts (500 to 1000) and generate this struct:
```
importContactsReq := client.ImportContactsRequest{
		Contacts: contactsToBeImported,
}
```
but when I call ```tdlibClient.ImportContacts(importContactsReq)``` method, I receive this error:
```
error: 429 Too Many Requests: retry after 3600
```
Although I haven't sent many requests to telegram server, I got this error!
At first I tried inserting 500 contacts and received the error, then I tried to add 100 contacts on another account and got that error again!
There isn't any way to insert batch of contacts (0 to 1000) in a single request?
because when I call the tdlibClient.ImportContacts method on every phone number that I have in my contact list, very soon I will get blocked :( even If i put a 1 minute delay between my requests :'(
Is there anyway to do this without these strange limits!? or your TDLib client can't add contacts just the way as Telegram client on mobile do (I have 1000 contacts on my phone and when I create new account and tick the "Sync Contacts" checkbox, It'll be done in a few seconds!)?

I should say that when I created the app Id and api hash_id on my telegram panel, I set the mode on "Desktop" one, can this cause this type of very tight limits?

**Comment by zelenin** [comment]
this is a wrapper over tdlib, so you can read  tdlib issues about it
https://github.com/tdlib/td/search?q=rate+limit&type=issues
