### ISSUE TITLE
How get more than 200 users from the chat?

### ISSUE THREAD

**Issue by jbc817** [zelenin/go-tdlib#40]
I have a group where contains 456 members, but i can get only 200 users, is there the to get they all, for example set offset parameter like in python in function get_chat_members from pyrogram"?
In python i can use function "get_chat_members" in "pyrogram" ans set offset parameter

I'm using that function "SearchChatMembers"  in my code

**Comment by zelenin** [comment]
use `GetSupergroupMembers`

**Comment by jbc817** [comment]
> use `GetSupergroupMembers`

It use int32 for id but chat use int64 for id

**Comment by zelenin** [comment]
you asked about it already https://github.com/zelenin/go-tdlib/issues/38

**Comment by jbc817** [comment]
you didn’t answer so I asked again

**Comment by zelenin** [comment]
i answered `this is chatId, not groupId.` Now we have supergroupId, not chatId.

**Comment by jbc817** [comment]
Sorry, I meant chat and not a group

**Comment by jbc817** [comment]
> i answered `this is chatId, not groupId.` Now we have supergroupId, not chatId.

So is there a way or not to get the chat list?

**Comment by zelenin** [comment]
if your chat is supergroup you can use `GetSupergroupMembers`
