### ISSUE TITLE
How to cast updates to an struct and what structs should be used.

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#41]
Hi Everyone.
Recenlty, I'm working on this code to analyze my telegram account events.
with the following code that is mentioned in the Readme.md of this project:
`for update := range listener.Updates {
		if update.GetClass() == client.ClassUpdate {
			log.Printf("%#v", update)
			if update.GetType() =="updateUser" {
				//updateStruct := update.(client.UpdateUserFullInfo)
			}
		}
	}`
I want to now, for exmaple if "update type" is "updateUser" , what struct should I use to cast the "update" variable into.
Or if update mode is UserStatus change like this:
```
2021/02/04 13:16:37 &client.UpdateUserStatus{meta:client.meta{Type:"", Extra:""}, UserId:1***2632, Status:(*client.UserStatusOffline)(0xc00020a060)}
```
What struct shall I use to cast the "update" into for being able to work with it's values, print them and so on in a more convenient way

**Comment by telexengineering** [comment]
@zelenin Dear Alexander, Can you help me with this matter?

**Comment by zelenin** [comment]
```go
    listener := tdlibClient.GetListener()
    defer listener.Close()

    for update := range listener.Updates {
        if update.GetClass() == client.ClassUpdate {
            if update.GetType() == client.TypeUpdateNewChat {
                updateNewChat := update.(*client.UpdateNewChat)
                log.Printf("%#v", updateNewChat)
            }

            // or

            updateNewMessage, ok := update.(*client.UpdateNewMessage)
            if ok {
                log.Printf("%#v", updateNewMessage)
            }

            // etc
            // https://github.com/zelenin/go-tdlib/blob/ec36320d03ff5c891bb45be1c14317c195eeadb9/client/type.go#L1028-L1108
        }
    }
```

**Comment by telexengineering** [comment]
thank you very much.
I will check this solution and will make you aware if any problem exists.
