### ISSUE TITLE
Invalid user.status data (or cached user.Status data)

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#43]
Hi
I'm working on this library to test and automate some of Telegram features for myself. Therefore, I logged into another phone number which I had by using this library and added my real phone number as a contact to it.
The first time I fetched my phone number's Telegram profile, everything seemed to be OK.
The second time, somethings were wrong. For example, the last seen stamp (Was online) was about 1 hour ago while my phone Telegram account was online at that moment.Moreover, OnlineStatus of my fetched profile was offline while my phone was online. I checked my phone from another phone which I had a real Telegram app on and everything was ok.
I think that `GetUser` method and `GetUserFullInfo` methods have some sort of cache because what I said.
Is there any method to disable and remove these caches? and be able to see profile of someone as it is in a real Telegram app without any lag?

**Comment by zelenin** [comment]
try ask here https://github.com/tdlib/td
go-tdlib is just wrapper
