### ISSUE TITLE
Error: Receive is called after Client destroy, or simultaneously from different threads

### ISSUE THREAD

**Issue by comerc** [zelenin/go-tdlib#45]
```go
	// Handle Ctrl+C
	ch := make(chan os.Signal, 2)
	signal.Notify(ch, os.Interrupt, syscall.SIGTERM)
	go func() {
		<-ch
		tdlibClient.Stop()
		os.Exit(1)
	}()
```

Workaround:

![Снимок экрана от 2021-03-22 00-50-48](https://user-images.githubusercontent.com/1025241/111922024-c047c580-8aa8-11eb-9033-b832192deb1e.png)

Solution by @levlam

> "Receive is called after Client destroy" is always a bug of those, who uses TDLib. You should move call to client.DestroyInstance() to the thread, which calls receive, instead of testing your luck with Sleep.
>
> You can also use new JSON interface (td_create_client_id/td_send/td_receive), which removes possibility to do this bug.

Please add support for td_create_client_id, td_send, td_receive, td_execute

https://core.telegram.org/tdlib/docs/td__json__client_8h.html

**Comment by comerc** [comment]
Related: https://github.com/zelenin/go-tdlib/issues/18

**Comment by zelenin** [comment]
https://github.com/zelenin/go-tdlib/releases/tag/v0.4.0
thanks for request
