### ISSUE TITLE
Failed to build project

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#47]
Hi.
I am using your project in my code as a dependency.
When I try to build my go application with the following command:
`
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags '-extldflags "-static" -X app.Version=v2021.04.03-140818-a6a2828 -X app.CommitHash=a6a2828f0aeabdd0f70657c014c504eb36d8f983' -o ./release/console bitbucket.org/tlxco/my-test-telegram-client/console
`
I will get the following errors:
`
# github.com/zelenin/go-tdlib/client
vendor/github.com/zelenin/go-tdlib/client/client.go:10:18: undefined: JsonClient
vendor/github.com/zelenin/go-tdlib/client/client.go:12:23: undefined: Response
vendor/github.com/zelenin/go-tdlib/client/client.go:107:43: undefined: Response
vendor/github.com/zelenin/go-tdlib/client/client.go:118:32: undefined: Request
vendor/github.com/zelenin/go-tdlib/client/client.go:118:43: undefined: Response
vendor/github.com/zelenin/go-tdlib/client/listener.go:50:16: undefined: Type
vendor/github.com/zelenin/go-tdlib/client/type.go:1550:2: undefined: meta
vendor/github.com/zelenin/go-tdlib/client/type.go:1571:2: undefined: meta
vendor/github.com/zelenin/go-tdlib/client/type.go:17252:2: undefined: meta
vendor/github.com/zelenin/go-tdlib/client/type.go:22766:2: undefined: meta
vendor/github.com/zelenin/go-tdlib/client/type.go:22766:2: too many errors
make: *** [build_console] Error 2
`
What should I do to resolve this build problems which are fired from this repo?

**Comment by telexengineering** [comment]
@zelenin Could you help me?

**Comment by yabeow** [comment]
Same problems here. Work fine in darwin but get these errors in linux :(

**Comment by telexengineering** [comment]
Dear @zelenin could you help us?

**Comment by telexengineering** [comment]
Dear @zelenin would you mind telling me what should I do in order to build the project?

**Comment by zelenin** [comment]
@telexengineering try module mode, not vendoring

**Comment by telexengineering** [comment]
@zelenin can you explain a bit more what you mean?

**Comment by zelenin** [comment]
https://blog.golang.org/using-go-modules
try to include the library in a project that supports modules. It is now included in the old-way project. Maybe this is the issue

**Comment by telexengineering** [comment]
@zelenin my project already has go modules. and I initiated the project and imported your code via this.
What's your other suggestion?

**Comment by zelenin** [comment]
> 
> 
> @zelenin my project already has go modules. and I initiated the project and imported your code via this.
> What's your other suggestion?

but I see `vendor` in your error. This is vendoring, not modules.

**Comment by telexengineering** [comment]
The problem solved.
I've used go modules but the problem had roots in using `-a -installsuffix cgo -ldflags '-extldflags "-static" -X app.Version=v2021.04.03-140818-a6a2828 -X app.CommitHash=a6a2828f0aeabdd0f70657c014c504eb36d8f983'` flags.
when I removed them everything gone well.
