### ISSUE TITLE
Possible solution for "Race condition in the new multi client design #1242"

### ISSUE THREAD

**Issue by livelace** [zelenin/go-tdlib#48]
Hello. I think you have already seen this issue [Race condition in the new multi client design #1242](https://github.com/tdlib/td/issues/1242).

TLDR: Since 1.7.0 receiving updates must be safe (mutually exclusive) between different threads. 

I use go-tdlib and see that this is a compex task to pass some shared mutex between threads tree, hence I have questions to you:

1. What do you think about this issue ? 
2. Maybe it's worthy to use some file locking in go-tdlib for threads synchronization ?

**Comment by zelenin** [comment]
go-tdlib supports the new client design already.
https://github.com/zelenin/go-tdlib/issues/45

**Comment by livelace** [comment]
Hm, it seems that doesn't work for me. I get this error just at the time of a second client creation (custom listeners are even not created yet). I tried go-tdlib 0.4 with tdlib 1.7.0.

**Comment by livelace** [comment]
**2netwalkers**

This short example will give you error:

```
[ 0][t 0][1618062097.475765943][Client.cpp:277] Receive is called after Client destroy, or simultaneously from different threads
```

Due to https://github.com/tdlib/td/blob/eb80924dad30af4e6d8385d058bb7e847174df5e/td/telegram/td_json_client.h#L70

So, I decided to make some small changes to my app and restrict it with one telegram client per instance, because I don't see an easy way to support multiple clients right now. 

```go
package main

import (
	"log"
	"path/filepath"
	"time"

	"github.com/zelenin/go-tdlib/client"
)

func getClient(d string) {
	// client authorizer
	authorizer := client.ClientAuthorizer()
	go client.CliInteractor(authorizer)

	const (
            apiId   = 00000
            apiHash = "8pu9yg32qkuukj83ozaqo5zzjwhkxhnk"
	)

	authorizer.TdlibParameters <- &client.TdlibParameters{
		UseTestDc:              false,
		DatabaseDirectory:      filepath.Join(d + "/.tdlib", "database"),
		FilesDirectory:         filepath.Join(d + "/.tdlib", "files"),
		UseFileDatabase:        true,
		UseChatInfoDatabase:    true,
		UseMessageDatabase:     true,
		UseSecretChats:         false,
		ApiId:                  apiId,
		ApiHash:                apiHash,
		SystemLanguageCode:     "en",
		DeviceModel:            "Server",
		SystemVersion:          "1.0.0",
		ApplicationVersion:     "1.0.0",
		EnableStorageOptimizer: true,
		IgnoreFileNames:        false,
	}

	logVerbosity := client.WithLogVerbosity(&client.SetLogVerbosityLevelRequest{
		NewVerbosityLevel: 0,
	})

	c, err := client.NewClient(authorizer, logVerbosity)
	me, err := c.GetMe()
	if err != nil {
		log.Fatalf("GetMe error: %s", err)
	}
	log.Printf("Me: %s %s [%s]", me.FirstName, me.LastName, me.Username)
}

func main() {
	go getClient("a")
	go getClient("b")

	time.Sleep(900 * time.Second)
}
```

**Comment by zelenin** [comment]
@livelace i will check it

**Comment by L11R** [comment]
Same problem :(

**Comment by askovpen** [comment]
[ 0][t 0][1619345016.295426607][Client.cpp:277] Receive is called after Client destroy, or simultaneously from different threads

**Comment by L11R** [comment]
Any news?

**Comment by askovpen** [comment]
fixed in https://github.com/zelenin/go-tdlib/commit/e5d2ffd3f9bf81a5fc4b1287ae8fb45a8763faa4
