### ISSUE TITLE
Give some examples

### ISSUE THREAD

**Issue by ArkIv** [zelenin/go-tdlib#52]
Show an example of how to get data as text using updateNewMessage as an example.
```
for update := range listener.Updates {
    if update.GetClass() == client.ClassUpdate {
	if update.GetType() == "updateNewMessage" {
                         ????
```

**Comment by zelenin** [comment]
you should cast to `UpdateNewMessage` and use it 
```updateNewMessage, ok := update.(*client.UpdateNewMessage)```
