### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by khoazero123** [zelenin/go-tdlib#56]
I have complete all step in this [guide](https://tdlib.github.io/td/build.html?language=Go) , after build done on Windows, I don't know what todo next ?
I have copy folder `tdlib\include\td` to `C:\Users\admin\go\pkg\mod\github.com\zelenin\go-tdlib@v0.4.0\client` 
and got some error when run this command in project folder `go get .`
```
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b057\_x002.o: in function `_cgo_06df6fcfe585_Cfunc_td_create_client_id':
/tmp/go-build/cgo-gcc-prolog:64: undefined reference to `__imp_td_create_client_id'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b057\_x002.o: in function `_cgo_06df6fcfe585_Cfunc_td_execute':
/tmp/go-build/cgo-gcc-prolog:82: undefined reference to `__imp_td_execute'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b057\_x002.o: in function `_cgo_06df6fcfe585_Cfunc_td_receive':
/tmp/go-build/cgo-gcc-prolog:100: undefined reference to `__imp_td_receive'
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b057\_x002.o: in function `_cgo_06df6fcfe585_Cfunc_td_send':
/tmp/go-build/cgo-gcc-prolog:117: undefined reference to `__imp_td_send'
collect2.exe: error: ld returned 1 exit status
```

**Comment by continue98** [comment]
Need use powershell with variable environment. For example:
```ps1
$env:CGO_LDFLAGS="-LPATH_TO_TD_JSON -ltdjson"
$env:CGO_CFLAGS="-IPATH_TO_INCLUDE"
```

in my case: 

```ps1
$env:CGO_LDFLAGS="-LR:\dev\tdlib\bin -ltdjson"
$env:CGO_CFLAGS="-IR:\dev\tdlib\include"
```

**Comment by vdntruong** [comment]
I have done almost stuff but get an error 😭 

`could not launch process: Process 13004 has exited with status 3221225781`

**Comment by donetkit** [comment]
API server listening at: 127.0.0.1:50662
could not launch process: Process 5812 has exited with status 3221225781

**Comment by donetkit** [comment]
I have done almost stuff but get an error  （ tdlib v1.7.0 ）

API server listening at: 127.0.0.1:50662
could not launch process: Process 5812 has exited with status 3221225781

**Comment by donetkit** [comment]
> I have done almost stuff but get an error （ tdlib v1.7.0 ）
> 
> API server listening at: 127.0.0.1:50662 could not launch process: Process 5812 has exited with status 3221225781

resolved 😄

**Comment by godcong** [comment]
1. create pkg uder your project
2. clone the project into pkg
3. see tdlib windows build use vcpkg: https://tdlib.github.io/td/build.html?language=Go
4.  create and run the client.


the example you can see my project:
https://github.com/motomototv/telebot
the clone scripts in my project:
```
#!/usr/bin/env bash

echo "Clone required repositories"
git clone https://github.com/zelenin/go-tdlib.git
git clone https://github.com/tdlib/td.git

echo "Copying files..."
cp -f ./backup/client/tdjson_dynamic.go ./go-tdlib/client/
cp -f ./backup/client/tdlib.go ./go-tdlib/client/

echo "Remove go.mod"
rm ./go-tdlib/go.mod
```

**Comment by zelenin** [comment]
added instruction to readme
