### ISSUE TITLE
"Library not found" error

### ISSUE THREAD

**Issue by vlabots** [zelenin/go-tdlib#63]
I copied folder tdlib/include/td on macos system to /Users/montie/go/pkg/mod/github.com/zelenin/go-tdlib@v0.4.1/client
and got some error when ran this command in project folder `go get .`

`# github.com/zelenin/go-tdlib/client
ld: library not found for -ltdjson_static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

What should I do?

Thank you for the answers.

**Comment by zelenin** [comment]
use https://tdlib.github.io/td/build.html?language=Go with checkmarked `Install built TDLib to /usr/local instead of placing the files to td/tdlib`
