### ISSUE TITLE
Telegram changes: sponsored messages and int64 for ids

### ISSUE THREAD

**Issue by livelace** [zelenin/go-tdlib#67]
Hi there. Recently received messages from Telegram about:

1. https://core.telegram.org/api/sponsored-messages
2. https://core.telegram.org/api/layers#layer-133

Corresponding issue in tdlib repo: [ Sponsored messages: Various questions #1753 ](https://github.com/tdlib/td/issues/1753)

It looks like we should have newer version of tdlib/go-tdlib to not be banned.
What do you think guys ?

**Comment by airani** [comment]
Hi,
Tdlib need upgrade to current version 1.7.9
https://github.com/tdlib/td/issues/1758
https://github.com/tdlib/td/issues/1753

**Comment by askovpen** [comment]
https://github.com/tdlib/td/issues/1753#issuecomment-981139816

**Comment by zelenin** [comment]
https://github.com/zelenin/go-tdlib/issues/69#issuecomment-1002658471
