### ISSUE TITLE
Generating the project code from tdlib/td

### ISSUE THREAD

**Issue by telexengineering** [zelenin/go-tdlib#69]
How can I create the code from the latest Tdlib schema that supports 64 bit IDs?
because I've problems with users whose ID is more than 2^32.
I need instruction to know how to generate go files in this project with the last version of TDLib which has some changes in some IDs (int32 to int36).

**Comment by godcong** [comment]
Can you tell me which api you have a problem with?
I didn't find a problem with the id in my fork, I replaced the so 32 bit with a 64 bit one.

**Comment by telexengineering** [comment]
@godcong Hi.
Thank you for your recommendation.
I've replaced zelenin/go-tdlib via your library and when I want to run some tdlib functions I get this panic:

[ 0][t 0][1640628525.754196882][Client.cpp:281] Receive is called after Client destroy, or simultaneously from different threads
SIGABRT: abort
PC=0x7f3ab76bc37f m=6 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f3ab76bc37f
stack: frame={sp:0x7f3a8f9188a0, fp:0x0} stack=[0x7f3a8f1191b0,0x7f3a8f918db0)

Do you know the solution?

**Comment by godcong** [comment]
This looks the client is already destroyed when you call the function.
Whether some Close or Stop function of the Client was called before this

**Comment by AlessandroPomponio** [comment]
Hello @telexengineering @godcong 

I have sent an email to the maintainer to see if he could update the library for everyone to include the latest changes that have been made to TDlib. Unfortunately the TDlib developers don't tag their code often enough and lots of things go under the radar. From some comments in the `tdlib/td` repository I have seen that they refer to the current version as `1.7.9`, despite not having tagged anything since `1.7.0`.

I've had a look at the code that is available in the current repository and I've seen that it seems quite simple to auto-generate the new code by changing the `TAG` variable in the `Makefile`. For example, to produce the code from the latest tdlib commit (`29e8df5` at the time of writing this) we can use that as the `TAG` in the `Makefile` and run 
```bash
make generate-code
```
This can also be done somewhat effortlessly by leveraging GitHub's codespaces by pressing `.` in the repository ^^

This is probably the best way to go about it, since there are too many things to update manually.

**Comment by zelenin** [comment]
Hey, guys. Remind you this is a tag-based wrapper. No tag - no update. 

I think the tdlib development team (@levlam) should change their approach to code tagging. He explained many times why he does this, but his explanations do not satisfy.

**Comment by zelenin** [comment]
for your own purposes, you can use the generator 

https://github.com/zelenin/go-tdlib/blob/master/Makefile

**Comment by telexengineering** [comment]
Hi.
I've updated the tdlib library (installed on my os) and now I'm receving this panic instead:
[ 0][t 0][1640793747.758627653][Client.cpp:282] Receive must not be called simultaneously from two different threads, but this has just happened. Call it from a fixed thread, dedicated for updates and response processing$
SIGABRT: abort
PC=0x7f0c4d304fff m=3 sigcode=18446744073709551610

I will check your code example and will let you know whether it works or not

**Comment by telexengineering** [comment]
> Hey, guys. Remind you this is a tag-based wrapper. No tag - no update.
> 
> I think the tdlib development team (@levlam) should change their approach to code tagging. He explained many times why he does this, but his explanations do not satisfy.

Do you mean that the new code which contains 64bit IDs doesn't exist in the library?

**Comment by livelace** [comment]
@zelenin I agree with your position, but we can use commit hash instead. What do you think ?

**Comment by livelace** [comment]
Should explain more. I'm from Gentoo world and it's pretty "normal" to use commit hash instead of tag/release for software building.

**Comment by AlessandroPomponio** [comment]
> Do you mean that the new code which contains 64bit IDs doesn't exist in the library?

It's not in the code available in this repository, as the TDlib developers haven't tagged version 1.8.0 yet.

> @zelenin I agree with your position, but we can use commit hash instead. What do you think ?

He said he will only update the library based on tagged versions, but you can generate the code yourself by changing the `TAG` variable in the `Makefile` like I've done here: https://github.com/shitpostingio/go-tdlib/tree/tdlib-29e8df5.
Later on I will try and see if I can sort of automate this process.

**Comment by livelace** [comment]
@AlessandroPomponio Yes and I can, but I don't want to make one more clone/fork, I want that original go-tdlib repo remains a good solution for golang + tdlib integration.

**Comment by AlessandroPomponio** [comment]
Yeah, I understand ^^
It must be your lucky day, they tagged 1.8.0 just a few hours ago, apparently :P

**Comment by livelace** [comment]
New Year Magic =)

**Comment by zelenin** [comment]
updated https://github.com/zelenin/go-tdlib/releases/tag/v0.5.0
