### ISSUE TITLE
Receive is called after Client destroy, or simultaneously from different threads

### ISSUE THREAD

**Issue by bodqhrohro** [zelenin/go-tdlib#70]
TDlib aborts with this error when a second client is created in a running instance.

As @levlam explained, in the new Client API the `td_receive` call is shared and the received updates should be dispatched to following clients. The binding has migrated to the new API in 98e8cb003f97653dc31d52bab0cfa6b7d28b99b9, but the receiving architecture wasn't updated accordingly, so every client has its own receive loop and they conflict, hence the problem.

So the binding in its current state is effectively incapable of handling multiple accounts at time, until a shared receiver routine is implemented.

**Comment by telexengineering** [comment]
Dear @zelenin could you help us with a solution to solve this problem?

**Comment by telexengineering** [comment]
Dear @levlam , Does it mean that we cant run different tdlib clients per different threads in one instance?

**Comment by bodqhrohro** [comment]
> Dear @zelenin could you help us with a solution to solve this problem?

They didn't pay attention for the project for about a month already. If it would persist, it's probably time to call the @godcong's fork a successor.

As a temporary solution, I just [rolled](https://github.com/bodqhrohro/go-tdlib/tree/old-api-revert) it back to the old API.

**Comment by levlam** [comment]
@telexengineering It means that you don't need to create a thread for each active client. The same thread must be used to handle responses and updates for all clients.

**Comment by telexengineering** [comment]
> 

So Why that panic happens?

**Comment by telexengineering** [comment]
> @telexengineering It means that you don't need to create a thread for each active client. The same thread must be used to handle responses and updates for all clients.
So Why Does that panic happen?

**Comment by levlam** [comment]
@telexengineering Because go-tdlib creates a thread for each client.

**Comment by telexengineering** [comment]
> @telexengineering Because go-tdlib creates a thread for each client.

@zelenin is it true?

**Comment by zelenin** [comment]
I think I know what the problem is. Need time for research.

**Comment by telexengineering** [comment]
> I think I know what the problem is. Need time for research.

Thank you very much.

**Comment by telexengineering** [comment]
Dear @gocong do you have a solution or idea about this problem?
Because my application development has been stopped because of this malfunction and I would become thrilled if you can help me.

**Comment by askovpen** [comment]
https://github.com/alexbilevskiy/go-tdlib/commit/6df7ea7c6881ab4c7fe2e40ff655a9f0099545c5

**Comment by telexengineering** [comment]
> alexbilevskiy@6df7ea7

Dear @zelenin do you approve this approach?

**Comment by telexengineering** [comment]
> alexbilevskiy@6df7ea7

Thank you for your suggestion

**Comment by telexengineering** [comment]
> alexbilevskiy@6df7ea7

Dear @zelenin, do you admit this approach?
By doing these changes, I mean, wouldn't there be other problems in other parts of the program?

**Comment by zelenin** [comment]
> [alexbilevskiy@6df7ea7](https://github.com/alexbilevskiy/go-tdlib/commit/6df7ea7c6881ab4c7fe2e40ff655a9f0099545c5)

yes, this is what we need.

I fixed some race conditions and released 0.5.1. 
The current code needs a little refactoring than I will do in the next year, but it already works for a multi-instance clients.

Thanks @askovpen for the code and everyone for your patience. Happy New Year!

**Comment by telexengineering** [comment]
> > [alexbilevskiy@6df7ea7](https://github.com/alexbilevskiy/go-tdlib/commit/6df7ea7c6881ab4c7fe2e40ff655a9f0099545c5)
> 
> yes, this is what we need.
> 
> I fixed some race conditions and released 0.5.1. The current code needs a little refactoring than I will do in the next year, but it already works for a multi-instance clients.
> 
> Thanks @askovpen for the code and everyone for your patience. Happy New Year!

Thank you from both of you @askovpen and @zelenin 
I will check the code and will let you know if the problem remains.

**Comment by askovpen** [comment]
For code thanks not me :-) thanks @alexbilevskiy
