### ISSUE TITLE
Is it possible to specify path to tdlib ?

### ISSUE THREAD

**Issue by borzovplus** [zelenin/go-tdlib#72]
Is it possible to specify path to tdlib, I complie tdlib in my project but, go-tdlib does not find that

**Comment by zelenin** [comment]
windows? added instruction to readme

**Comment by borzovplus** [comment]
no, linux, my steps: from macbook I compile with help docker tldlib for linux, then move libtdjson.so to linux server (I can not compile on the server, because it os very slow)

**Comment by borzovplus** [comment]
> windows? added instruction to readme

no, linux, my steps:
from macbook I compile with help docker tldlib for linux, then move libtdjson.so to linux server (I can not compile on the server, because it os very slow)

**Comment by zelenin** [comment]
the same way - use environment variables

**Comment by borzovplus** [comment]
> the same way - use environment variables. or are you talking about a compiled application?

sorry for my stupid questions (
I'm talking only about ibtdjson.so
I downloaded libtdjson.so and libtdjson.so.1.8.0  to my ubuntu server(I compiled it and upload to gitlab) and where should I move it on the server? What are environment variables I should specify before run my golang application?

**Comment by zelenin** [comment]
do static builds (by default) that don't need .so

**Comment by borzovplus** [comment]
How I can build golang application with shared lib libtdjson.so ? Is it possible?) Or from where static build take this shared lib to compile golang application?

**Comment by borzovplus** [comment]
> do static builds (by default) that don't need .so

How I can build golang application with shared lib libtdjson.so ? Is it possible?) Or from where static build take this shared lib to compile golang application?

**Comment by borzovplus** [comment]
> 

I tired copy this lib to /usr/local/lib, but get this error when try build golang app:
fatal error: td/telegram/td_json_client.h: No such file or directory
#20 12.29  #include <td/telegram/td_json_client.h>

**Comment by zelenin** [comment]
build according to the instructions, select the installation to /usr/local and see where what will be installed 
https://tdlib.github.io/td/build.html

`go build ...` will make a static build, `go build -libtdjson` - dynamic.

if you have non-standard installation paths, use environment variables as in Windows example

**Comment by borzovplus** [comment]
> 

2 sleepless nights, and haven't moved yet (
All necessary files (such as libtd*.a and libtd*.so, telegram/ and tl/) in /usr/local/include and /usr/local/libs are there
I have standard installation paths.


I tired: 
1) go build -libtdjson
But have error: 

> flag provided but not defined: -libtdjson


2) go build -linkshared
But have a lot of such errors:

> 19 92.94 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: telegram_api.cpp:(.text._ZNK2td12telegram_api42channelAdminLogEventActionToggleNoForwards5storeERNS_16TlStorerToStringEPKc+0x106): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
> #19 92.94 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib/libtdcore.a(telegram_api.cpp.o): in function `td::telegram_api::channelAdminLog


3) go build -linkshared --ldflags "-extldflags '-static -L/usr/local/lib -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdactor -ltddb -ltdsqlite -ltdnet -ltdutils -ldl -lm -lssl -lcrypto -lstdc++ -lz'"

I had the same errors as in 2)

**Comment by borzovplus** [comment]
> build according to the instructions, select the installation to `/usr/local` and see where what will be installed https://tdlib.github.io/td/build.html
> 
> `go build ...` will make a static build, `go build -libtdjson ...` - dynamic.
> 
> if you have non-standard installation paths, use environment variables as in Windows example

> 

2 sleepless nights, and haven't moved yet (
All necessary files (such as libtd*.a and libtd*.so, telegram/ and tl/) in /usr/local/include and /usr/local/libs are there
I have standard installation paths.


I tired: 
1) go build -libtdjson
But have error: 

> flag provided but not defined: -libtdjson


2) go build -linkshared
But have a lot of such errors:

> 19 92.94 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: telegram_api.cpp:(.text._ZNK2td12telegram_api42channelAdminLogEventActionToggleNoForwards5storeERNS_16TlStorerToStringEPKc+0x106): undefined reference to `std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::append(char const*)'
> #19 92.94 /usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/local/lib/libtdcore.a(telegram_api.cpp.o): in function `td::telegram_api::channelAdminLog


3) go build -linkshared --ldflags "-extldflags '-static -L/usr/local/lib -ltdjson_static -ltdjson_private -ltdclient -ltdcore -ltdactor -ltddb -ltdsqlite -ltdnet -ltdutils -ldl -lm -lssl -lcrypto -lstdc++ -lz'"

I had the same errors as in 2)
