### ISSUE TITLE
Tdlight support

### ISSUE THREAD

**Issue by e2e-rnd-host** [zelenin/go-tdlib#73]
Hello!, Do you have plans about https://github.com/tdlight-team/tdlight supporting ?
If no, could you advise me in which places it is necessary to make changes to support new tdlib parameters and a new method TdApi.GetMemoryStatistics ?

**Comment by zelenin** [comment]
you can just replace tdlib with tdlight

**Comment by e2e-rnd-host** [comment]
> GetMemoryStatistics

But TdlibParameters does not have extnded parameters such as:
disable_minithumbnails (true/false) 
disable_document_filenames (true/false) 
disable_notifications (true/false)
ignore_update_chat_last_message (true/false)
ignore_update_chat_read_inbox (true/false)
ignore_update_user_chat_action (true/false) 
ignore_server_deletes_and_reads (true/false)
receive_access_hashes (true/false) 

and also how I can call GetMemoryStatistics method (this method was be added only in tdlight)?

**Comment by e2e-rnd-host** [comment]
> you can just replace tdlib with tdlight

But TdlibParameters does not have extnded parameters such as:
disable_minithumbnails (true/false)
disable_document_filenames (true/false)
disable_notifications (true/false)
ignore_update_chat_last_message (true/false)
ignore_update_chat_read_inbox (true/false)
ignore_update_user_chat_action (true/false)
ignore_server_deletes_and_reads (true/false)
receive_access_hashes (true/false)

and also how I can call GetMemoryStatistics method (this method was be added only in tdlight)?
