### ISSUE TITLE
Request: Support calling synchronous methods without client

### ISSUE THREAD

**Issue by arisudesu** [zelenin/go-tdlib#74]
The tdlib has number of functions, marked in td_api.tl, that they could be called synchronously, such as [this one](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl#L4544). These are utility functions that don't require client ID to work and they return the result immediately.

It could be possible to call them via library without calling NewClient too.

**Comment by zelenin** [comment]
https://github.com/zelenin/go-tdlib/releases/tag/v0.6.0
