### ISSUE TITLE
TDLib 1.8.1 support

### ISSUE THREAD

**Issue by kvikuz** [zelenin/go-tdlib#77]
Hi, can you support TDLib 1.8.1?

**Comment by zelenin** [comment]
Client code is generated from the latest stable version of the tdlib schema. Waiting for a new tag
https://github.com/tdlib/td/releases

**Comment by mxmCherry** [comment]
There will be no tag, they don't tag patch versions.

Potentially addressed by https://github.com/zelenin/go-tdlib/pull/83
