### ISSUE TITLE
Errors during compiling

### ISSUE THREAD

**Issue by Fef0** [zelenin/go-tdlib#79]
Hi @zelenin, I tried to use this library both with tdlib 1.8.3 and 1.6.0 but every time that I try to compile I get these errors:
```
# github.com/zelenin/go-tdlib/client
../../../../zelenin/go-tdlib/client/tdlib.go:130:11: could not determine kind of name for C.td_create_client_id
../../../../zelenin/go-tdlib/client/tdlib.go:105:12: could not determine kind of name for C.td_execute
../../../../zelenin/go-tdlib/client/tdlib.go:81:12: could not determine kind of name for C.td_receive
../../../../zelenin/go-tdlib/client/tdlib.go:141:2: could not determine kind of name for C.td_send
```

Any idea why?

Thanks in advance

**Comment by MarlikAlmighty** [comment]
I have the same error. But go-tdlib v0.6.0 and /usr/local/lib/libtdjson.so.1.8.14

**Comment by zelenin** [comment]
use supported version of tdlib from README or https://github.com/zelenin/go-tdlib/tree/master/example
