### ISSUE TITLE
Handle updates based on certain criteria (filter) [help wanted]

### ISSUE THREAD

**Issue by itshaadi** [zelenin/go-tdlib#8]
How can I for example react to new messages that are forwarded?

```go
tdlibClient, err := client.NewClient(authorizer, WithLogs())
if err != nil {
	log.Fatalf("NewClient error: %s", err)
} else {
	log.Println("Ready !")
}

listener := tdlibClient.GetListener()
defer listener.Close()

for update := range listener.Updates {
	if update.GetType() == client.TypeUpdateNewMessage {
		// ???
	}
}
```

**Comment by johnbalvin** [comment]
Could you show authorizer configuration? , I'm having an error and I'm not quite sure what I'm doing wrong

**Comment by itshaadi** [comment]
Is it something along the lines of `!is_locked failed` ? And then spits out
a bunch of memory addresses?

Because I'm getting an error as well without applying any changes to the
authorizer (except for hash and id). And even with the basic example.

It hsppend last night, maybe they changed or deprecated some methods again?

**Comment by zelenin** [comment]
```go
    for update := range listener.Updates {
        if update.GetType() == client.TypeUpdateNewMessage {
            message := update.(*client.UpdateNewMessage)
            if message.Message.ForwardInfo != nil {
                log.Print("Bingo!")
            }
        }
    }
```
