### ISSUE TITLE
I have the error  with build golang app

### ISSUE THREAD

**Issue by dAvagimyan** [zelenin/go-tdlib#85]
I have created docker image with the installing tdlib library and golang app. I didn't have error when i installed tdlib, but when i tried build my app , i got this error.  
<img width="807" alt="Снимок экрана 2022-10-03 в 10 53 35" src="https://user-images.githubusercontent.com/18144616/193527099-81491648-eb54-409a-be6d-8022fe1649b5.png">

Does Anybody knows what i can do with it ?  Below i presented my docker image.

`FROM dokken/ubuntu-22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get upgrade && \
    apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake clang-14 libc++-dev libc++abi-dev

RUN git clone https://github.com/tdlib/td.git

ENV CXXFLAGS="-stdlib=libc++"
ENV CC=/usr/bin/clang-14
ENV CXX=/usr/bin/clang++-14

RUN cd td && \
    git checkout v1.7.0 && \
    rm -rf build &&  \
    mkdir build &&  \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local -DTD_ENABLE_LTO=ON -DCMAKE_AR=/usr/bin/llvm-ar-14 -DCMAKE_NM=/usr/bin/llvm-nm-14 -DCMAKE_OBJDUMP=/usr/bin/llvm-objdump-14 -DCMAKE_RANLIB=/usr/bin/llvm-ranlib-14 .. && \
    cmake --build . --target install

RUN ls -l /usr/local`

**Comment by Chrizpy** [comment]
Hi, do you still have the same issue?

I was curious about this project too but I ended up with the same issues as you.

I stumbled across this [issue](https://github.com/tdlib/td/issues/1244) where [levlam](https://github.com/levlam) claims to have built it with no issues on a fresh install of Ubuntu 20.

I used this Docker image:

```Dockerfile
# syntax=docker/dockerfile:1.4
FROM ubuntu:focal

ENV DEBIAN_FRONTEND=noninteractive
RUN <<EOF
  apt-get update
  apt-get upgrade
  apt-get install -y make git zlib1g-dev libssl-dev gperf php-cli cmake clang-10 libc++-dev libc++abi-dev wget vim
  git clone https://github.com/tdlib/td.git
  cd td
  rm -rf build
  mkdir build
  cd build
  CXXFLAGS="-stdlib=libc++" CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
  cmake --build . --target install
  cd ..
  cd ..
  ls -l /usr/local
EOF
```

I was also able to build it with `clang` on `ubuntu:focal (20.04)`, but not on `ubuntu:jammy (22.04)`. I was not able to build the example project in the [`README`](https://github.com/zelenin/go-tdlib) however.

I tried building the project with `g++` instead, but on `ubuntu:jammy`, and that worked but was really slow. Using that I could (at least I think?) build the example project in the `README`.

Gonna test some more tomorrow I think.

**Comment by dAvagimyan** [comment]
Hi! I  have changed a docker image,  i did it when i use alpine image.

```
FROM golang:1.18-alpine as builder

RUN apk add --no-cache \
    gperf \
    linux-headers \
    alpine-sdk \
    php \
    openssl-dev \
    git \
    cmake \
    zlib-dev

WORKDIR /tmp/_build_tdlib/

RUN git clone https://github.com/tdlib/td.git /tmp/_build_tdlib/ --branch v1.8.0

RUN mkdir build
WORKDIR /tmp/_build_tdlib/build/

RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
RUN cmake --build . --target install
RUN make install


RUN apk add --no-cache  \
    gcc
```
