### ISSUE TITLE
Chinese garbled code

### ISSUE THREAD

**Issue by fangdididi** [zelenin/go-tdlib#86]
How to solve the problem that the Chinese data returned by the Windows 10 request is garbled in traditional Chinese

![微信截图_20230107014248](https://user-images.githubusercontent.com/42022630/211068445-7ab11cb0-d445-4868-b5a9-2abdd7cd84e7.png)

**Comment by fangdididi** [comment]
At present, the terminal uses git bash, and the code has been set to utf-8. The same code is normally requested in Linux, but it is garbled in Windows
![微信截图_20230107014728](https://user-images.githubusercontent.com/42022630/211069156-4546c349-6d0a-42bb-be11-ce3380a6c0f4.png)

**Comment by chenyu1990** [comment]
没有遇到过这个问题

**Comment by zelenin** [comment]
not a library issue
