### ISSUE TITLE
How to make a Dockerfile for building Go app based on go-tdlib and TDLib

### ISSUE THREAD

**Issue by dimau** [zelenin/go-tdlib#87]
Hi Aleksandr!

Appreciate your work here, thank you for your efforts! 
I would like to ask you give me some additional instructions or example (and maybe add them in README.md) - how to build TDLib and then Go app based on your library in Docker image? 

It would be great to have an example of Dockerfile for that

**Comment by zelenin** [comment]
added https://github.com/zelenin/go-tdlib#example

**Comment by dimau** [comment]
Thank you! 
Just checked all is working perfectly and it can be a simple start for newcomers in Telegram API like me :)
