### ISSUE TITLE
Where is the DeleteChatHistory() function?

### ISSUE THREAD

**Issue by omani** [zelenin/go-tdlib#88]
how am I supposed to call the function `DeleteChatHistory()`in `functions.go`? it is in the `client` package but I can't access it.

**Comment by zelenin** [comment]
```
ok, err := tdlibClient.DeleteChat(&client.DeleteChatRequest{ChatId: chatId})
```

**Comment by omani** [comment]
thank you.

**Comment by lepehovsv** [comment]
> thank you.
> how am I supposed to call the function `DeleteChatHistory()`in `functions.go`? it is in the `client` package but I can't access it.
@omani Sorry to write here, I couldn't find your contacts. I've made small additions to the go-monero-rpc-client code. Could you take a look at the pull request? https://github.com/monero-ecosystem/go-monero-rpc-client/pull/15
