### ISSUE TITLE
Building with docker container

### ISSUE THREAD

**Issue by fomotrader** [zelenin/go-tdlib#93]
Firstly thanks for this fantastic project 

I've copied your example and I'm trying to build with the docker container on  DigitalOcean's App Platform, It took over 50 mins to build and I found after tdlib was built that there was a bug in the docker script. 

Could you help suggest a quicker way to install tdlib?

**Comment by zelenin** [comment]
https://github.com/zelenin/go-tdlib/tree/master/example

**Comment by fomotrader** [comment]
Yh this definitely works but is extremely slow because we build tdlib from scratch

**Comment by zelenin** [comment]
Ah, that's the problem. look for a prebuilt tldib in the package manager of your OS of the required version

**Comment by fomotrader** [comment]
@zelenin would you be interested in helping me getting it working, paid of course, check your email for more details
