### ISSUE TITLE
update code

### ISSUE THREAD

**Issue by krlspj** [zelenin/go-tdlib#95]
I was able to run your program localy but in puller package, chats.go file there is this error:
the GetChatsRequests structure does not have the mentioned fiels
![image](https://github.com/zelenin/go-tdlib/assets/43220110/501cd0fa-2d52-4b66-90fe-23baec499a68)

I'm also trying to run the tl-parser with new version of td_api.tl but seams it generate some wrong code:
![image](https://github.com/zelenin/go-tdlib/assets/43220110/07e9ba01-e57b-48b7-8353-1dc97b329b09)

Idk if could you help me to fix it?

**Comment by zelenin** [comment]
I deleted Chats because it used an outdated api. Try last versiob
