### ISSUE TITLE
Could you tell me how to use the specific send message mode ?

### ISSUE THREAD

**Issue by dylanpoe** [zelenin/go-tdlib#98]
I use SendMessageRequest  to send message, but I cannot find how to make sure  the message display mode ? such as  MARKDOWN V2 ,or  HTML ?
How to pass the display mode parameters?

**Comment by zelenin** [comment]
```
	text := "text"

	formattedText, err := client.ParseTextEntities(&client.ParseTextEntitiesRequest{
		Text:      text,
		ParseMode: &client.TextParseModeMarkdown{Version: 2},
	})

	msg, err := tdlibClient.SendMessage(&client.SendMessageRequest{
		ChatId:              0,
		MessageThreadId:     0,
		ReplyTo:             nil,
		Options:             nil,
		ReplyMarkup:         nil,
		InputMessageContent: &client.InputMessageText{
			Text:                  formattedText,
			DisableWebPagePreview: false,
			ClearDraft:            false,
		},
	})
```

**Comment by dylanpoe** [comment]
thank you so much

**Comment by dylanpoe** [comment]
I  use the methods, but the effect is not showed as markdown in TG frontclient,
here is my text sample:

☘️\(foobar\) foobar [foobar 🎲 foobar]\(https://t\.me/foobar \)
📊 foobar:  $1\K

🔰foobar: foobar\(foobar\)

🔎 [foobar: foobar]\(https://foobar\.io/app/foobar/foobar/foobar\-foobar/foobar\) 

But the TG client just disply as 


☘️(foobar) foobar [foobar 🎲 foobar](https://t.me/foobar )
📊 foobar:  $1K

🔰foobar: foobar(foobar)

🔎 [foobar: foobar](https://foobar.io/app/foobar/foobar/foobar-foobar/foobar) 


What I wish is the text just showed as they showed in the markdown formats, like url is url is hiden ,not showed,just in markdown url showed

Thank you

**Comment by dylanpoe** [comment]
I  combined the string in golang  use  this marks  ``

fmt.Sprintf(``)

Did the methods  referenced the display results?

**Comment by dylanpoe** [comment]
> I combined the string in golang use this marks ``
> 
> fmt.Sprintf(``)
> 
> Did the methods referenced the display results?

Already solved ,thank you !
The reason is the text should not contains any escape marks \ , just plain string
And the version should be  1, not 2
